# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca gem bigdecimal`.


# pkg:gem/bigdecimal#lib/bigdecimal.rb:4
class BigDecimal < ::Numeric
  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def %(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def *(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def **(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def +(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def +@; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def -(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def -@; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def /(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def <(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def <=(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def <=>(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def ==(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def ===(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def >(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def >=(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def _dump(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def abs; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def add(_arg0, _arg1); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def ceil(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def clone; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def coerce(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def div(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def divmod(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def dup; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def eql?(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def exponent; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def finite?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def fix; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def floor(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def frac; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def hash; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def infinite?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def inspect; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def modulo(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def mult(_arg0, _arg1); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def n_significant_digits; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def nan?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def nonzero?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def power(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def precision; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def precision_scale; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def precs; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def quo(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def remainder(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def round(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def scale; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def sign; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def split; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def sqrt(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def sub(_arg0, _arg1); end

  # call-seq:
  #     a.to_d -> bigdecimal
  #
  # Returns self.
  #
  #     require 'bigdecimal/util'
  #
  #     d = BigDecimal("3.14")
  #     d.to_d                       # => 0.314e1
  #
  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:110
  def to_d; end

  # call-seq:
  #     a.to_digits -> string
  #
  # Converts a BigDecimal to a String of the form "nnnnnn.mmm".
  # This method is deprecated; use BigDecimal#to_s("F") instead.
  #
  #     require 'bigdecimal/util'
  #
  #     d = BigDecimal("3.14")
  #     d.to_digits                  # => "3.14"
  #
  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:90
  def to_digits; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def to_f; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def to_i; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def to_int; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def to_r; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def to_s(format = T.unsafe(nil)); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def truncate(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
  def zero?; end

  class << self
    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def _load(_arg0); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def double_fig; end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def interpret_loosely(_arg0); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def limit(*_arg0); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def mode(*_arg0); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def save_exception_mode; end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def save_limit; end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:4
    def save_rounding_mode; end
  end
end

BigDecimal::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/bigdecimal#lib/bigdecimal/util.rb:138
class Complex < ::Numeric
  # call-seq:
  #     cmp.to_d             -> bigdecimal
  #     cmp.to_d(precision)  -> bigdecimal
  #
  # Returns the value as a BigDecimal.
  #
  # The +precision+ parameter is required for a rational complex number.
  # This parameter is used to determine the number of significant digits
  # for the result.
  #
  #     require 'bigdecimal'
  #     require 'bigdecimal/util'
  #
  #     Complex(0.1234567, 0).to_d(4)   # => 0.1235e0
  #     Complex(Rational(22, 7), 0).to_d(3)   # => 0.314e1
  #
  # See also Kernel.BigDecimal.
  #
  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:157
  def to_d(*args); end
end
