# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `byebug` gem.
# Please instead update this file by running `bin/tapioca gem byebug`.


# Main Container for all of Byebug's code
#
#
# Main debugger's container module. Everything is defined under this module
#
#
# Namespace for all of byebug's code
#
#
# Remote debugging functionality.
#
#
# Reopen main module to define the library version
#
# pkg:gem/byebug#lib/byebug/attacher.rb:6
module Byebug
  class << self
    # Starts byebug, and stops at the first line of user's code.
    #
    # pkg:gem/byebug#lib/byebug/attacher.rb:10
    def attach; end

    # pkg:gem/byebug#lib/byebug/attacher.rb:21
    def spawn(host = T.unsafe(nil), port = T.unsafe(nil)); end
  end
end

# Adds a `byebug` method to the Kernel module.
#
# Dropping a `byebug` call anywhere in your code, you get a debug prompt.
#
# pkg:gem/byebug#lib/byebug/attacher.rb:34
module Kernel
  # pkg:gem/byebug#lib/byebug/attacher.rb:35
  def byebug; end

  # pkg:gem/byebug#lib/byebug/attacher.rb:47
  def debugger; end

  # pkg:gem/byebug#lib/byebug/attacher.rb:41
  def remote_byebug(host = T.unsafe(nil), port = T.unsafe(nil)); end
end
