# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `require-hooks` gem.
# Please instead update this file by running `bin/tapioca gem require-hooks`.


# pkg:gem/require-hooks#lib/require-hooks/api.rb:3
module RequireHooks
  class << self
    # Define a block to wrap the code loading.
    # The return value MUST be a result of calling the passed block.
    # For example, you can use such hooks for instrumentation, debugging purposes.
    #
    #    RequireHooks.around_load do |path, &block|
    #      puts "Loading #{path}"
    #      block.call.tap { puts "Loaded #{path}" }
    #    end
    #
    # pkg:gem/require-hooks#lib/require-hooks/api.rb:90
    def around_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:144
    def context_for(path); end

    # This hook should be used to manually compile byte code to be loaded by the VM.
    # The arguments are (path, source = nil), where source is only defined if transformations took place.
    # Otherwise, you MUST read the source code from the file yourself.
    #
    # The return value MUST be either nil (continue to the next hook or default behavior) or a platform-specific bytecode object (e.g., RubyVM::InstructionSequence).
    #
    #   RequireHooks.hijack_load do |path, source|
    #     source ||= File.read(path)
    #     if defined?(RubyVM::InstructionSequence)
    #       RubyVM::InstructionSequence.compile(source)
    #     elsif defined?(JRUBY_VERSION)
    #       JRuby.compile(source)
    #     end
    #   end
    #
    # pkg:gem/require-hooks#lib/require-hooks/api.rb:134
    def hijack_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:80
    def print_warnings; end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:80
    def print_warnings=(_arg0); end

    # Define hooks to perform source-to-source transformations.
    # The return value MUST be either String (new source code) or nil (indicating that no transformations were performed).
    #
    # NOTE: The second argument (`source`) MAY be nil, indicating that no transformer tried to transform the source code.
    #
    #
    #    RequireHooks.source_transform do |path, source|
    #    end
    #
    # pkg:gem/require-hooks#lib/require-hooks/api.rb:110
    def source_transform(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end
  end
end

# pkg:gem/require-hooks#lib/require-hooks/api.rb:4
class RequireHooks::Context
  # pkg:gem/require-hooks#lib/require-hooks/api.rb:8
  def initialize(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil)); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def around_load; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:29
  def empty?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def exclude_patterns; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:38
  def hijack?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def hijack_load; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:23
  def match?(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def patterns; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:52
  def perform_source_transform(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:42
  def run_around_load_callbacks(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def source_transform; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:34
  def source_transform?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:19
  def to_key; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:64
  def try_hijack_load(path, source); end
end

# pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:4
RequireHooks::EMPTY_ISEQ = T.let(T.unsafe(nil), RubyVM::InstructionSequence)

# pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:6
module RequireHooks::LoadIseq
  # pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:7
  def load_iseq(path); end
end

class RubyVM::InstructionSequence
  extend ::RequireHooks::LoadIseq
end
