# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubydex` gem.
# Please instead update this file by running `bin/tapioca gem rubydex`.


# frozen_string_literal: true
# typed: strict

# pkg:gem/rubydex#lib/rubydex/version.rb:3
module Rubydex; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::AttrAccessorDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::AttrReaderDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::AttrWriterDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Class < ::Rubydex::Namespace; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ClassDefinition < ::Rubydex::Definition
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T.nilable(Rubydex::ConstantReference)) }
  def superclass; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ClassVariable < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ClassVariableDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Comment
  # pkg:gem/rubydex#lib/rubydex/comment.rb:12
  sig { params(string: String, location: Rubydex::Location).void }
  def initialize(string:, location:); end

  # pkg:gem/rubydex#lib/rubydex/comment.rb:9
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex/comment.rb:6
  sig { returns(String) }
  def string; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Constant < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ConstantAlias < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ConstantAliasDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ConstantDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ConstantReference < ::Rubydex::Reference
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(Rubydex::Location) }
  def location; end

  class << self
    def new(*args); end
  end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ConstantVisibilityDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def name; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(Rubydex::Declaration) }
  def owner; end

  # @abstract
  #
  # pkg:gem/rubydex#lib/rubydex/declaration.rb:7
  sig { returns(T::Enumerable[Rubydex::Reference]) }
  def references; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def unqualified_name; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:11
    def new(*args); end
  end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Definition
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Comment]) }
  def comments; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Boolean) }
  def deprecated?; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def name; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T.nilable(Rubydex::Location)) }
  def name_location; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:11
    def new(*args); end
  end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Diagnostic
  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:15
  sig { params(rule: Symbol, message: String, location: Rubydex::Location).void }
  def initialize(rule:, message:, location:); end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:12
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:9
  sig { returns(String) }
  def message; end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:6
  sig { returns(Symbol) }
  def rule; end
end

# A one based location intended for display purposes. This is what should be used when displaying a location to users,
# like in CLIs
#
# pkg:gem/rubydex#lib/rubydex/location.rb:70
class Rubydex::DisplayLocation < ::Rubydex::Location
  # Normalize to zero-based for comparison with Location
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:81
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # Returns itself
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:74
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:86
  sig { returns(String) }
  def to_s; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Document
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def uri; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:11
    def new(*args); end
  end
end

class Rubydex::Error < StandardError; end

# Represents `extend SomeModule`
#
# pkg:gem/rubydex#lib/rubydex/mixin.rb:21
class Rubydex::Extend < ::Rubydex::Mixin; end

# pkg:gem/rubydex#lib/rubydex/failures.rb:4
class Rubydex::Failure
  # pkg:gem/rubydex#lib/rubydex/failures.rb:9
  sig { params(message: String).void }
  def initialize(message); end

  # pkg:gem/rubydex#lib/rubydex/failures.rb:6
  sig { returns(String) }
  def message; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::GlobalVariable < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::GlobalVariableAliasDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::GlobalVariableDefinition < ::Rubydex::Definition; end

# The global graph representing all declarations and their relationships for the workspace
#
# Note: this class is partially defined in C to integrate with the Rust backend
#
# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Graph
  # pkg:gem/rubydex#lib/rubydex/graph.rb:24
  sig { params(workspace_path: T.nilable(String)).void }
  def initialize(workspace_path: T.unsafe(nil)); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(fully_qualified_name: String).returns(T.nilable(Rubydex::Declaration)) }
  def [](fully_qualified_name); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Failure]) }
  def check_integrity; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  # Returns completion candidates for an expression context. This includes all keywords, constants, methods, instance
  # variables, class variables and global variables reachable from the current lexical scope and self type.
  #
  # The nesting array represents the lexical scope stack, where the last element is the self type. An empty array
  # defaults to `Object` as the self type (top-level context).
  sig { params(nesting: T::Array[String]).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword)]) }
  def complete_expression(nesting); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  # Returns completion candidates inside a method call's argument list (e.g., `foo.bar(|)`). This includes everything
  # that expression completion provides plus keyword argument names of the method being called.
  #
  # The nesting array represents the lexical scope stack, where the last element is the self type.
  sig do
    params(
      name: String,
      nesting: T::Array[String]
    ).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword, Rubydex::KeywordParameter)])
  end
  def complete_method_argument(name, nesting); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  # Returns completion candidates after a method call operator (e.g., `foo.`). This includes all methods that exist on
  # the type of the receiver and its ancestors.
  sig { params(name: String).returns(T::Array[Rubydex::Method]) }
  def complete_method_call(name); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  # Returns completion candidates after a namespace access operator (e.g., `Foo::`). This includes all constants and
  # singleton methods for the namespace and its ancestors.
  sig { params(name: String).returns(T::Array[Rubydex::Declaration]) }
  def complete_namespace_access(name); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def constant_references; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def declarations; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def delete_document(uri); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Document]) }
  def documents; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(encoding: String).void }
  def encoding=(encoding); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(paths: T::Array[String]).void }
  def exclude_paths(paths); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[String]) }
  def excluded_paths; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(query: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def fuzzy_search(query); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(file_paths: T::Array[String]).returns(T::Array[String]) }
  def index_all(file_paths); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(uri: String, source: String, language_id: String).void }
  def index_source(uri, source, language_id); end

  # Index all files and dependencies of the workspace that exists in `@workspace_path`
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:32
  sig { returns(T::Array[String]) }
  def index_workspace; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  def keyword(_arg0); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(load_paths: T::Array[String]).returns(T::Array[String]) }
  def require_paths(load_paths); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T.self_type) }
  def resolve; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(name: String, nesting: T::Array[String]).returns(T.nilable(Rubydex::Declaration)) }
  def resolve_constant(name, nesting); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(require_path: String, load_paths: T::Array[String]).returns(T.nilable(Rubydex::Document)) }
  def resolve_require_path(require_path, load_paths); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(query: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def search(query); end

  # pkg:gem/rubydex#lib/rubydex/graph.rb:21
  sig { returns(String) }
  def workspace_path; end

  # pkg:gem/rubydex#lib/rubydex/graph.rb:21
  sig { params(workspace_path: String).returns(String) }
  def workspace_path=(workspace_path); end

  # Returns all workspace paths that should be indexed, excluding directories that we don't need to descend into such
  # as `.git`, `node_modules`. Also includes any top level Ruby files
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:40
  sig { returns(T::Array[String]) }
  def workspace_paths; end

  private

  # Searches for the latest installation of the `rbs` gem and adds the paths for the core and stdlib RBS definitions
  # to the list of paths. This method does not require `rbs` to be a part of the bundle. It searches for whatever
  # latest installation of `rbs` exists in the system and fails silently if we can't find one
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:87
  sig { params(paths: T::Array[String]).void }
  def add_core_rbs_definition_paths(paths); end

  # Gathers the paths we have to index for all workspace dependencies
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:63
  sig { params(paths: T::Array[String]).void }
  def add_workspace_dependency_paths(paths); end
end

# pkg:gem/rubydex#lib/rubydex/graph.rb:8
Rubydex::Graph::IGNORED_DIRECTORIES = T.let(T.unsafe(nil), Array)

# Represents `include SomeModule`
#
# pkg:gem/rubydex#lib/rubydex/mixin.rb:15
class Rubydex::Include < ::Rubydex::Mixin; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::InstanceVariable < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::InstanceVariableDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex/failures.rb:14
class Rubydex::IntegrityFailure < ::Rubydex::Failure; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Keyword
  # pkg:gem/rubydex#lib/rubydex/keyword.rb:12
  sig { params(name: String, documentation: String).void }
  def initialize(name, documentation); end

  # pkg:gem/rubydex#lib/rubydex/keyword.rb:9
  sig { returns(String) }
  def documentation; end

  # pkg:gem/rubydex#lib/rubydex/keyword.rb:6
  sig { returns(String) }
  def name; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::KeywordParameter
  # pkg:gem/rubydex#lib/rubydex/keyword_parameter.rb:9
  sig { params(name: String).void }
  def initialize(name); end

  # pkg:gem/rubydex#lib/rubydex/keyword_parameter.rb:6
  sig { returns(String) }
  def name; end
end

# A zero based internal location. Intended to be used for tool-to-tool communication, such as a language server
# communicating with an editor.
#
# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Location
  include ::Comparable

  # pkg:gem/rubydex#lib/rubydex/location.rb:18
  sig { params(uri: String, start_line: Integer, end_line: Integer, start_column: Integer, end_column: Integer).void }
  def initialize(uri:, start_line:, end_line:, start_column:, end_column:); end

  # pkg:gem/rubydex#lib/rubydex/location.rb:38
  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other); end

  # pkg:gem/rubydex#lib/rubydex/location.rb:45
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def end_column; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def end_line; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def start_column; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def start_line; end

  # Turns this zero based location into a one based location for display purposes.
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:52
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:27
  sig { returns(String) }
  def to_file_path; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:63
  sig { returns(String) }
  def to_s; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:12
  sig { returns(String) }
  def uri; end
end

# pkg:gem/rubydex#lib/rubydex/location.rb:7
class Rubydex::Location::NotFileUriError < ::StandardError; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Method < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def references; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::MethodAliasDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::MethodDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::MethodReference < ::Rubydex::Reference
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def name; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::MethodVisibilityDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex/mixin.rb:4
class Rubydex::Mixin
  # pkg:gem/rubydex#lib/rubydex/mixin.rb:9
  sig { params(constant_reference: Rubydex::ConstantReference).void }
  def initialize(constant_reference); end

  # pkg:gem/rubydex#lib/rubydex/mixin.rb:6
  def constant_reference; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Module < ::Rubydex::Namespace; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ModuleDefinition < ::Rubydex::Definition
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Namespace < ::Rubydex::Declaration
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def ancestors; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def descendants; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  def find_member(*_arg0); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { params(name: String).returns(T.nilable(Rubydex::Declaration)) }
  def member(name); end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def members; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T.nilable(Rubydex::SingletonClass)) }
  def singleton_class; end
end

# Represents `prepend SomeModule`
#
# pkg:gem/rubydex#lib/rubydex/mixin.rb:18
class Rubydex::Prepend < ::Rubydex::Mixin; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Reference
  # pkg:gem/rubydex#lib/rubydex.rb:11
  def initialize(_arg0, _arg1); end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:11
    def new(*args); end
  end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::ResolvedConstantReference < ::Rubydex::ConstantReference
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(Rubydex::Declaration) }
  def declaration; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::SingletonClass < ::Rubydex::Namespace; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::SingletonClassDefinition < ::Rubydex::Definition
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::Todo < ::Rubydex::Namespace; end

# pkg:gem/rubydex#lib/rubydex.rb:11
class Rubydex::UnresolvedConstantReference < ::Rubydex::ConstantReference
  # pkg:gem/rubydex#lib/rubydex.rb:11
  sig { returns(String) }
  def name; end
end

# pkg:gem/rubydex#lib/rubydex/version.rb:4
Rubydex::VERSION = T.let(T.unsafe(nil), String)
