# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lsp` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lsp`.

# source://ruby-lsp-0.2.1/lib/ruby-lsp.rb:4
module RubyLsp; end

# source://ruby-lsp-0.2.1/lib/ruby-lsp.rb:5
RubyLsp::VERSION = T.let(T.unsafe(nil), String)
