# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `smart_properties` gem.
# Please instead update this file by running `bin/tapioca gem smart_properties`.


# {SmartProperties} can be used to easily build more full-fledged accessors
# for standard Ruby classes. In contrast to regular accessors,
# {SmartProperties} support validation and conversion of input data, as well
# as, the specification of default values. Additionally, individual
# {SmartProperties} can be marked as required. This causes the runtime to
# throw an +ArgumentError+ whenever a required property has not been
# specified.
#
# In order to use {SmartProperties}, simply include the {SmartProperties}
# module and use the {ClassMethods#property} method to define properties.
#
# @see ClassMethods#property
#   More information on how to configure properties
#
# @example Definition of a property that makes use of all {SmartProperties} features.
#
#  property :language_code, :accepts => [:de, :en],
#                           :converts => :to_sym,
#                           :default  => :de,
#                           :required => true
#
# pkg:gem/smart_properties#lib/smart_properties.rb:23
module SmartProperties
  mixes_in_class_methods ::SmartProperties::ClassMethods

  # Implements a key-value enabled constructor that acts as default
  # constructor for all {SmartProperties}-enabled classes. Positional arguments
  # or keyword arguments that do not correspond to a property are forwarded to
  # the super class constructor.
  #
  # @param [Hash] attrs the set of attributes that is used for initialization
  #
  # @raise [SmartProperties::ConstructorArgumentForwardingError] when unknown arguments were supplied that could not be processed by the super class initializer either.
  # @raise [SmartProperties::InitializationError] when incorrect values were supplied or required values weren't been supplied.
  #
  # pkg:gem/smart_properties#lib/smart_properties.rb:127
  def initialize(*args, &block); end

  # pkg:gem/smart_properties#lib/smart_properties.rb:165
  def [](name); end

  # pkg:gem/smart_properties#lib/smart_properties.rb:172
  def []=(name, value); end

  class << self
    private

    # Extends the class, which this module is included in, with a property
    # method to define properties.
    #
    # @param [Class] base the class this module is included in
    #
    # pkg:gem/smart_properties#lib/smart_properties.rb:110
    def included(base); end
  end
end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:5
class SmartProperties::AssignmentError < ::SmartProperties::Error
  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:9
  def initialize(sender, property, message); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:7
  def property; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:7
  def property=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:6
  def sender; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:6
  def sender=(_arg0); end
end

# pkg:gem/smart_properties#lib/smart_properties.rb:24
module SmartProperties::ClassMethods
  # Returns a class's smart properties. This includes the properties that
  # have been defined in the parent classes.
  #
  # @return [Hash<String, Property>] A map of property names to property instances.
  #
  # pkg:gem/smart_properties#lib/smart_properties.rb:31
  def properties; end

  protected

  # Defines a new property from a name and a set of options. This results
  # results in creating an accessor that has additional features:
  #
  # 1. Validation of input data by specifiying the +:accepts+ option:
  #    If you use a class as value for this option, the setter will check
  #    if the value it is about to assign is of this type. If you use an
  #    array, the setter will check if the value it is about to assign is
  #    included in this array. Finally, if you specify a block, it will
  #    invoke the block with the value it is about to assign and check if
  #    the block returns a thruthy value, meaning anything but +false+ and
  #    +nil+.
  #
  # 2. Conversion of input data by specifiying the +:converts+ option:
  #    If you use provide a symbol as value for this option, the setter will
  #    invoke this method on the object it is about to assign and take the
  #    result of this call instead. If you provide a block, it will invoke
  #    the block with the value it is about to assign and take the result
  #    of the block instead.
  #
  # 3. Providing a default value by specifiying the +:default+ option.
  #
  # 4. Forcing a property to be present by setting the +:required+ option
  #    to true.
  #
  #
  # @param [Symbol] name the name of the property
  #
  # @param [Hash] options the list of options used to configure the property
  # @option options [Array, Class, Proc] :accepts
  #   specifies how the validation is done
  # @option options [Proc, Symbol] :converts
  #   specifies how the conversion is done
  # @option options :default
  #   specifies the default value of the property
  # @option options [true, false] :required
  #   specifies whether or not this property is required
  #
  # @return [Property] The defined property.
  #
  # @example Definition of a property that makes use of all {SmartProperties} features.
  #
  #  property :language_code, :accepts => [:de, :en],
  #                           :converts => :to_sym,
  #                           :default  => :de,
  #                           :required => true
  #
  # pkg:gem/smart_properties#lib/smart_properties.rb:82
  def property(name, **options); end

  # pkg:gem/smart_properties#lib/smart_properties.rb:87
  def property!(name, **options); end
end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:3
class SmartProperties::ConfigurationError < ::SmartProperties::Error; end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:16
class SmartProperties::ConstructorArgumentForwardingError < ::SmartProperties::Error
  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:17
  def initialize(positional_arguments, keyword_arguments); end

  private

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:33
  def generate_description(argument_type, argument_number); end
end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:2
class SmartProperties::Error < ::ArgumentError; end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:95
class SmartProperties::InitializationError < ::SmartProperties::Error
  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:99
  def initialize(sender, properties); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:97
  def properties; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:97
  def properties=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:96
  def sender; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:96
  def sender=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:110
  def to_hash; end
end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:62
class SmartProperties::InvalidValueError < ::SmartProperties::AssignmentError
  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:65
  def initialize(sender, property, value); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:80
  def to_hash; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:63
  def value; end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:63
  def value=(_arg0); end

  private

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:86
  def accepter_message(sender, property); end
end

# pkg:gem/smart_properties#lib/smart_properties/errors.rb:45
class SmartProperties::MissingValueError < ::SmartProperties::AssignmentError
  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:46
  def initialize(sender, property); end

  # pkg:gem/smart_properties#lib/smart_properties/errors.rb:57
  def to_hash; end
end

# pkg:gem/smart_properties#lib/smart_properties.rb:94
module SmartProperties::ModuleMethods
  # pkg:gem/smart_properties#lib/smart_properties.rb:95
  def included(target); end
end

# pkg:gem/smart_properties#lib/smart_properties/property.rb:2
class SmartProperties::Property
  # pkg:gem/smart_properties#lib/smart_properties/property.rb:17
  def initialize(name, **attrs); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:8
  def accepter; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:78
  def accepts?(value, scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:62
  def convert(scope, value); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:7
  def converter; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:74
  def default(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:98
  def define(klass); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:136
  def get(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:10
  def instance_variable_name; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:49
  def missing?(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:6
  def name; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:45
  def optional?(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:89
  def prepare(scope, value); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:53
  def present?(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:9
  def reader; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:41
  def required?(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:122
  def set(scope, value); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:126
  def set_default(scope); end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:141
  def to_h; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:11
  def writable; end

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:57
  def writable?; end

  private

  # pkg:gem/smart_properties#lib/smart_properties/property.rb:155
  def null_object?(object); end

  class << self
    # pkg:gem/smart_properties#lib/smart_properties/property.rb:13
    def define(scope, name, **options); end
  end
end

# pkg:gem/smart_properties#lib/smart_properties/property.rb:4
SmartProperties::Property::ALLOWED_DEFAULT_CLASSES = T.let(T.unsafe(nil), Array)

# pkg:gem/smart_properties#lib/smart_properties/property.rb:3
SmartProperties::Property::MODULE_REFERENCE = T.let(T.unsafe(nil), Symbol)

# pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:2
class SmartProperties::PropertyCollection
  include ::Enumerable

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:23
  def initialize; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:37
  def [](name); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:29
  def []=(name, value); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:53
  def each(&block); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:41
  def key?(name); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:45
  def keys; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:5
  def parent; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:62
  def register(child); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:58
  def to_hash; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:49
  def values; end

  protected

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:70
  def children; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:70
  def children=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:71
  def collection; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:71
  def collection=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:72
  def collection_with_parent_collection; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:72
  def collection_with_parent_collection=(_arg0); end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:74
  def notify_children; end

  # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:78
  def refresh(parent_collection); end

  class << self
    # pkg:gem/smart_properties#lib/smart_properties/property_collection.rb:7
    def for(scope); end
  end
end

# pkg:gem/smart_properties#lib/smart_properties/version.rb:2
SmartProperties::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/smart_properties#lib/smart_properties/validations.rb:4
module SmartProperties::Validations; end

# pkg:gem/smart_properties#lib/smart_properties/validations/ancestor.rb:4
class SmartProperties::Validations::Ancestor
  include ::SmartProperties
  extend ::SmartProperties::ClassMethods

  # pkg:gem/smart_properties#lib/smart_properties/validations/ancestor.rb:13
  def to_proc; end

  # pkg:gem/smart_properties#lib/smart_properties/validations/ancestor.rb:18
  def to_s; end

  # pkg:gem/smart_properties#lib/smart_properties/validations/ancestor.rb:9
  def validate(klass); end

  class << self
    # pkg:gem/smart_properties#lib/smart_properties/validations/ancestor.rb:23
    def must_be(*_arg0); end
  end
end
