# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `spring` gem.
# Please instead update this file by running `bin/tapioca gem spring`.


# ### WHY SPRING VENDORS A JSON LIBRARY ###
#
# Spring is designed to be able to run outside of bundler. Ruby has a
# built-in "json" library, which we could use. However if we require
# that, and somebody has a different (perhaps newer) version of the
# json *gem* in their Gemfile, it will never get used since we already
# required the older version of the json library from the stdlib.
# Therefore, we are vendoring a json library for our own use in order to
# not interfere.
# Some parts adapted from
# https://golang.org/src/pkg/json/decode.go and
# https://golang.org/src/pkg/utf8/utf8.go
#
# pkg:gem/spring#lib/spring/watcher/abstract.rb:5
module Spring
  class << self
    # pkg:gem/spring#lib/spring/configuration.rb:30
    def after_fork(&block); end

    # pkg:gem/spring#lib/spring/configuration.rb:26
    def after_fork_callbacks; end

    # pkg:gem/spring#lib/spring/configuration.rb:5
    def application_root; end

    # pkg:gem/spring#lib/spring/configuration.rb:5
    def application_root=(_arg0); end

    # pkg:gem/spring#lib/spring/configuration.rb:38
    def application_root_path; end

    # pkg:gem/spring#lib/spring/commands.rb:19
    def command(name); end

    # pkg:gem/spring#lib/spring/commands.rb:15
    def command?(name); end

    # pkg:gem/spring#lib/spring/commands.rb:8
    def commands; end

    # pkg:gem/spring#lib/spring/configuration.rb:7
    def gemfile; end

    # pkg:gem/spring#lib/spring/configuration.rb:17
    def gemfile_lock; end

    # pkg:gem/spring#lib/spring/configuration.rb:51
    def project_root_path; end

    # pkg:gem/spring#lib/spring/configuration.rb:5
    def quiet; end

    # pkg:gem/spring#lib/spring/configuration.rb:5
    def quiet=(_arg0); end

    # pkg:gem/spring#lib/spring/commands.rb:11
    def register_command(name, command = T.unsafe(nil)); end

    # pkg:gem/spring#lib/spring/configuration.rb:34
    def verify_environment; end

    # pkg:gem/spring#lib/spring/watcher.rb:27
    def watch(*items); end

    # pkg:gem/spring#lib/spring/watcher.rb:6
    def watch_interval; end

    # pkg:gem/spring#lib/spring/watcher.rb:6
    def watch_interval=(_arg0); end

    # pkg:gem/spring#lib/spring/watcher.rb:8
    def watch_method; end

    # pkg:gem/spring#lib/spring/watcher.rb:11
    def watch_method=(method); end

    # pkg:gem/spring#lib/spring/watcher.rb:23
    def watcher; end

    # pkg:gem/spring#lib/spring/watcher.rb:7
    def watcher=(_arg0); end

    private

    # pkg:gem/spring#lib/spring/configuration.rb:57
    def find_project_root(current_dir); end
  end
end

# pkg:gem/spring#lib/spring/errors.rb:2
class Spring::ClientError < ::StandardError; end

# pkg:gem/spring#lib/spring/errors.rb:34
class Spring::CommandNotFound < ::Spring::ClientError; end

# pkg:gem/spring#lib/spring/command_wrapper.rb:4
class Spring::CommandWrapper
  # pkg:gem/spring#lib/spring/command_wrapper.rb:7
  def initialize(name, command = T.unsafe(nil)); end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:60
  def binstub; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:64
  def binstub_name; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:36
  def call; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:5
  def command; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:13
  def description; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:76
  def env(args); end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:68
  def exec; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:52
  def exec_name; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:44
  def gem_name; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:5
  def name; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:25
  def setup; end

  # pkg:gem/spring#lib/spring/command_wrapper.rb:21
  def setup?; end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:2
module Spring::Commands; end

# pkg:gem/spring#lib/spring/commands/rails.rb:3
class Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:4
  def call; end

  # pkg:gem/spring#lib/spring/commands/rails.rb:9
  def description; end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:14
class Spring::Commands::RailsConsole < ::Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:31
  def command_name; end

  # pkg:gem/spring#lib/spring/commands/rails.rb:15
  def env(args); end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:42
class Spring::Commands::RailsDestroy < ::Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:43
  def command_name; end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:36
class Spring::Commands::RailsGenerate < ::Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:37
  def command_name; end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:48
class Spring::Commands::RailsRunner < ::Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:49
  def call; end

  # pkg:gem/spring#lib/spring/commands/rails.rb:58
  def command_name; end

  # pkg:gem/spring#lib/spring/commands/rails.rb:54
  def env(args); end

  # pkg:gem/spring#lib/spring/commands/rails.rb:62
  def extract_environment(args); end
end

# pkg:gem/spring#lib/spring/commands/rails.rb:86
class Spring::Commands::RailsTest < ::Spring::Commands::Rails
  # pkg:gem/spring#lib/spring/commands/rails.rb:101
  def command_name; end

  # pkg:gem/spring#lib/spring/commands/rails.rb:87
  def env(args); end
end

# pkg:gem/spring#lib/spring/commands/rake.rb:3
class Spring::Commands::Rake
  # pkg:gem/spring#lib/spring/commands/rake.rb:13
  def env(args); end

  class << self
    # pkg:gem/spring#lib/spring/commands/rake.rb:5
    def environment_matchers; end

    # pkg:gem/spring#lib/spring/commands/rake.rb:5
    def environment_matchers=(_arg0); end
  end
end

# pkg:gem/spring#lib/spring/errors.rb:18
class Spring::MissingApplication < ::Spring::ClientError
  # pkg:gem/spring#lib/spring/errors.rb:21
  def initialize(project_root); end

  # pkg:gem/spring#lib/spring/errors.rb:25
  def message; end

  # pkg:gem/spring#lib/spring/errors.rb:19
  def project_root; end
end

# pkg:gem/spring#lib/spring/errors.rb:4
class Spring::UnknownProject < ::StandardError
  # pkg:gem/spring#lib/spring/errors.rb:7
  def initialize(current_dir); end

  # pkg:gem/spring#lib/spring/errors.rb:5
  def current_dir; end

  # pkg:gem/spring#lib/spring/errors.rb:11
  def message; end
end

# pkg:gem/spring#lib/spring/watcher/abstract.rb:6
module Spring::Watcher; end

# A user of a watcher can use IO.select to wait for changes:
#
#   watcher = MyWatcher.new(root, latency)
#   IO.select([watcher]) # watcher is running in background
#   watcher.stale? # => true
#
# pkg:gem/spring#lib/spring/watcher/abstract.rb:12
class Spring::Watcher::Abstract
  include ::Mutex_m

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:17
  def initialize(root, latency); end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:38
  def add(*items); end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:34
  def debug; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:15
  def directories; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:15
  def files; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:15
  def latency; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:13
  def lock; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:13
  def locked?; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:91
  def mark_stale; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:30
  def on_debug(&block); end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:86
  def on_stale(&block); end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:98
  def restart; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:15
  def root; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:82
  def stale?; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:104
  def start; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:108
  def stop; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:112
  def subjects_changed; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:13
  def synchronize(&block); end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:13
  def try_lock; end

  # pkg:gem/spring#lib/spring/watcher/abstract.rb:13
  def unlock; end
end

# pkg:gem/spring#lib/spring/watcher/polling.rb:5
class Spring::Watcher::Polling < ::Spring::Watcher::Abstract
  # pkg:gem/spring#lib/spring/watcher/polling.rb:8
  def initialize(root, latency); end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:24
  def add(*_arg0); end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:14
  def check_stale; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:6
  def mtime; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:60
  def running?; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:29
  def start; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:52
  def stop; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:64
  def subjects_changed; end

  private

  # pkg:gem/spring#lib/spring/watcher/polling.rb:72
  def compute_mtime; end

  # pkg:gem/spring#lib/spring/watcher/polling.rb:93
  def expanded_files; end
end
