inherit_gem:
    rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  UseCache: true
  SuggestExtensions: false
  CacheRootDirectory: tmp
  Exclude:
    - 'test/fixtures/**/*'

Sorbet/ConstantsFromStrings:
  Enabled: true

Sorbet/ForbidIncludeConstLiteral:
  Enabled: true

Sorbet/SignatureBuildOrder:
  Enabled: true

Sorbet/KeywordArgumentOrdering:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true

Performance/AncestorsInclude: # new in 1.7
  Enabled: true

Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true

Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true

Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true

Performance/ConstantRegexp: # new in 1.9
  Enabled: true

Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true

Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true

Performance/RedundantSortBlock: # new in 1.7
  Enabled: true

Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true

Performance/RedundantStringChars: # new in 1.7
  Enabled: true

Performance/ReverseFirst: # new in 1.7
  Enabled: true

Performance/SortReverse: # new in 1.7
  Enabled: true

Performance/Squeeze: # new in 1.7
  Enabled: true

Performance/StringInclude: # new in 1.7
  Enabled: true

Performance/Sum: # new in 1.8
  Enabled: true
